version: '3'

services:
  nginx:
    image: library/nginx:1.19.2-alpine
    ports:
    - '80:80'
    depends_on:
    - app
    volumes:
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - .:/var/www/html

  app:
    build: ./docker/php
    working_dir: /var/www/html/app
    volumes:
    - ./app:/var/www/html/app
    depends_on:
    - postgres

  postgres:
    image: postgres:11.9-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
    - "5432:5432"
    volumes:
    - ./postgres/init:/docker-entrypoint-initdb.d
